### ISSUE TITLE
Error: Cannot find package "tmeasday:check-npm-versions". Try "meteor add tmeasday:check-npm-versions".

### ISSUE THREAD

**Issue by ScottAgirs** [copleykj/socialize-cloudinary#2]
After `$ meteor add socialize:cloudinary `

I get the following error:
```
=> Meteor server restarted
W20180911-23:04:05.472(-4)? (STDERR) /Users/.meteor/packages/meteor-tool/.1.7.0_3.w8zcf.uowlh++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180911-23:04:05.473(-4)? (STDERR) 						throw(ex);
W20180911-23:04:05.474(-4)? (STDERR) 						^
W20180911-23:04:05.474(-4)? (STDERR)
W20180911-23:04:05.475(-4)? (STDERR) Error: Cannot find package "tmeasday:check-npm-versions". Try "meteor add tmeasday:check-npm-versions".
W20180911-23:04:05.475(-4)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:597:13)
W20180911-23:04:05.475(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:230:14)
W20180911-23:04:05.476(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180911-23:04:05.476(-4)? (STDERR)     at versionCheck.js (packages/socialize:cloudinary/server/versionCheck.js:1:35)
W20180911-23:04:05.476(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180911-23:04:05.477(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180911-23:04:05.477(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180911-23:04:05.477(-4)? (STDERR)     at server.js (packages/socialize:cloudinary/server/server.js:1:300)
W20180911-23:04:05.493(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180911-23:04:05.494(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180911-23:04:05.494(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180911-23:04:05.495(-4)? (STDERR)     at /Users/workspace/projectname/.meteor/local/build/programs/server/packages/socialize_cloudinary.js:174:15
W20180911-23:04:05.495(-4)? (STDERR)     at /Users/workspace/projectname/.meteor/local/build/programs/server/packages/socialize_cloudinary.js:179:3
W20180911-23:04:05.495(-4)? (STDERR)     at /Users/workspace/projectname/.meteor/local/build/programs/server/boot.js:411:36
W20180911-23:04:05.497(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20180911-23:04:05.497(-4)? (STDERR)     at /Users/workspace/projectname/.meteor/local/build/programs/server/boot.js:220:19
W20180911-23:04:05.497(-4)? (STDERR)     at /Users/workspace/projectname/.meteor/local/build/programs/server/boot.js:471:5
W20180911-23:04:05.508(-4)? (STDERR)     at Function.run (/Users/workspace/projectname/.meteor/local/build/programs/server/profile.js:510:12)
W20180911-23:04:05.508(-4)? (STDERR)     at /Users/workspace/projectname/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
```

**meteor/packages file:**
```

meteor-base@1.4.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.5.0                   # The database Meteor supports right now
static-html                   # Define static page content in .html files
tracker@1.2.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.4.1   # CSS minifier run for production mode
standard-minifier-js@2.3.4    # JS minifier run for production mode
es5-shim@4.8.0                # ECMAScript 5 compatibility for older browsers
ecmascript              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command

apollo
accounts-password
mrgalaxy:stripe
meteorhacks:aggregate
meteortesting:mocha
accounts-facebook
service-configuration
meteorhacks:async
socialize:cloudinary

```
package.json:
```
{
  "name": "appname",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.51",
    "apollo-client": "^2.3.7",
    "apollo-client-preset": "^1.0.8",
    "babel-plugin-inline-import": "^3.0.0",
    "bcrypt": "^3.0.0",
    "body-parser": "^1.18.3",
    "cloudinary": "^1.11.0",
    "cloudinary-core": "^2.5.0",
    "date-fns": "^1.29.0",
    "express": "^4.16.3",
    "faker": "^4.1.0",
    "google-map-react": "^1.0.6",
    "graphql": "^0.13.2",
    "graphql-server-express": "^1.4.0",
    "graphql-tag": "^2.9.2",
    "graphql-tools": "^3.1.1",
    "lodash": "^4.17.10",
    "meteor-node-stubs": "^0.4.1",
    "moment": "^2.22.2",
    "moment-duration-format": "^2.2.2",
    "react": "^16.4.2",
    "react-apollo": "^2.1.9",
    "react-dom": "^16.4.2",
    "react-map-gl": "^3.3.4",
    "react-places-autocomplete": "^7.2.0",
    "react-router-dom": "^4.3.1",
    "react-stripe-elements": "^2.0.1",
    "react-toastify": "^4.3.1",
    "semantic-ui-calendar-react": "^0.8.0",
    "semantic-ui-react": "^0.82.2",
    "stripe": "^6.8.0",
    "styled-components": "^3.4.1"
  },
  "devDependencies": {
    "chai": "^4.1.2"
  }
}

```

**Comment by copleykj** [comment]
Looks like it was left out of the package deps. I'll see about getting a fix out.. In the mean time adding the package to your app and making sure it is listed before this packages in the app's `.meteor/packages` file should fix the issue.
